version: '3'

services:
    web:
        build:
            context: .
        volumes:
            - ./:/usr/src/app
        command: sh -c "cd react-ec && yarn start"
        ports:
            - "3000:3000"
        stdin_open: true